spring.application.name=Gimnasio

spring.datasource.url=jdbc:postgresql://localhost:5432/golds_gym
spring.datasource.username=postgres
spring.datasource.password=admin1234

# Generación automática de tablas y logs de SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
